INSERT INTO recipes (title, description, ingredients, user_id, like_count)
VALUES
    ('Pollo al Horno con Patatas y Cebolla', 'Deliciosa receta de pollo al horno acompañado de patatas y cebolla.', '[["pollo", 1], ["patatas", 4], ["cebolla", 1], ["aceite de oliva", 2], ["sal", 1], ["pimienta", 1], ["romero", 1]]', 1, 0),
    ('Garbanzos con Espinacas', 'Plato saludable y sabroso de garbanzos con espinacas.', '[["garbanzos", 1], ["espinacas", 200], ["cebolla", 1], ["ajo", 2], ["comino", 1], ["pimentón", 1], ["aceite de oliva", 2], ["limón", 1], ["sal", 1]]', 1, 0),
    ('Espaguetis con Salsa de Tomate', 'Clásica receta de espaguetis con salsa de tomate casera.', '[["espaguetis", 200], ["tomate", 4], ["cebolla", 1], ["ajo", 2], ["albahaca", 1], ["orégano", 1], ["aceite de oliva", 2], ["sal", 1], ["pimienta", 1]]', 1, 0),
    ('Galletas de Mantequilla Caseras', 'Aprende a hacer galletas de mantequilla crujientes en casa.', '[["harina", 250], ["mantequilla", 150], ["azúcar", 100], ["huevo", 1], ["esencia de vainilla", 1], ["sal", 1]]', 1, 0),
    ('Lasagna de Carne', 'Deliciosa lasaña casera con carne molida, salsa de tomate y queso.', '[["pasta de lasaña", 12], ["carne molida", 500], ["salsa de tomate", 800], ["cebolla", 1], ["ajo", 3], ["queso ricotta", 250], ["queso mozzarella", 200], ["queso parmesano", 100], ["huevo", 1], ["albahaca", 1], ["orégano", 1], ["aceite de oliva", 2], ["sal", 1], ["pimienta", 1]]', 1, 0),
    ('Ensalada César', 'Clásica ensalada César con pollo a la parrilla y aderezo cremoso.', '[["pollo", 1], ["lechuga romana", 1], ["crutones", 100], ["queso parmesano", 50], ["aceite de oliva", 2], ["limón", 1], ["anchoas", 3], ["ajo", 1], ["mostaza Dijon", 1], ["salsa Worcestershire", 1], ["huevo", 1], ["sal", 1], ["pimienta", 1]]', 1, 0),
    ('Salmón a la Parrilla', 'Filete de salmón jugoso a la parrilla con limón y eneldo.', '[["filete de salmón", 1], ["limón", 1], ["eneldo", 1], ["aceite de oliva", 2], ["sal", 1], ["pimienta", 1]]', 1, 0),
    ('Ratatouille', 'Plato francés de verduras asadas con hierbas provenzales.', '[["berenjena", 1], ["calabacín", 1], ["pimiento rojo", 1], ["pimiento amarillo", 1], ["tomate", 2], ["cebolla", 1], ["ajo", 2], ["albahaca", 1], ["tomillo", 1], ["romero", 1], ["aceite de oliva", 2], ["sal", 1], ["pimienta", 1]]', 1, 0),
    ('Tacos de Carne Asada', 'Tacos mexicanos rellenos de carne asada, cebolla y cilantro.', '[["carne de res", 400], ["tortillas de maíz", 12], ["cebolla", 1], ["cilantro", 1], ["limón", 1], ["pimiento picante", 1], ["comino", 1], ["paprika", 1], ["ajo en polvo", 1], ["aceite de oliva", 2], ["sal", 1], ["pimienta", 1]]', 1, 0),
    ('Risotto de Champiñones', 'Risotto cremoso con champiñones salteados y queso parmesano.', '[["arroz Arborio", 200], ["champiñones", 150], ["cebolla", 1], ["ajo", 2], ["vino blanco", 100], ["caldo de verduras", 500], ["queso parmesano", 100], ["mantequilla", 50], ["aceite de oliva", 2], ["sal", 1], ["pimienta", 1]]', 1, 0),
    ('Curry de Pollo', 'Plato de pollo cocinado en una deliciosa salsa de curry con especias.', '[["pollo", 400], ["cebolla", 1], ["tomate", 2], ["jengibre", 1], ["ajo", 3], ["curry en polvo", 2], ["comino", 1], ["cúrcuma", 1], ["cilantro molido", 1], ["leche de coco", 400], ["aceite de oliva", 2], ["sal", 1]]', 1, 0),
    ('Pizza Margherita', 'Pizza clásica con salsa de tomate, mozzarella y albahaca fresca.', '[["masa de pizza", 1], ["salsa de tomate", 150], ["mozzarella", 200], ["albahaca", 1], ["aceite de oliva", 2], ["sal", 1], ["pimienta", 1]]', 1, 0),
    ('Pastel de Chocolate', 'Delicioso pastel de chocolate con glaseado y decoración.', '[["harina", 250], ["azúcar", 200], ["chocolate negro", 200], ["mantequilla", 150], ["huevos", 3], ["esencia de vainilla", 1], ["levadura en polvo", 1], ["sal", 1]]', 1, 0),
    ('Sopa de Tomate', 'Sopa reconfortante de tomate con un toque de albahaca.', '[["tomate", 4], ["cebolla", 1], ["zanahoria", 1], ["ajo", 2], ["caldo de pollo", 500], ["albahaca", 1], ["aceite de oliva", 2], ["sal", 1], ["pimienta", 1]]', 1, 0);
